rod_server/config/routes.rb
Rails.application.routes.draw do

  scope '/api' do
    devise_for :users, :controllers => { :registrations => "registrations" }
    resources :groups
    resources :builders
    post 'search' => 'builders#search'
  end

  devise_scope :user do
    post 'api/users/sign_out_post(.:format)' => 'devise/sessions#destroy'
  end
end
  

rod_server/app/models/builder.rb
class Builder < ActiveRecord::Base
  include PgSearch
  belongs_to :user

  pg_search_scope :search, 
                  :against => [:species, :rodtype, :ship, :location, :poleblank],
                  :using => {
                    :tsearch => {:any_word => true}
                  }

  # This method associates the attribute ":image" with a file attachment
  has_attached_file :image,
                    :styles => {large: "1000x1000>", medium: "300x300>", thumb: "100x100#"},
                    default_url: "/images/:style/missing.png"

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def image_url
    image.url(:medium)
  end

  def email
    user.email
  end
end

rod_server/app/models/group.rb
class Group < ActiveRecord::Base
end

rod_server/app/models/post.rb
class Post < ActiveRecord::Base
end

rod_server/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :builder
end

rod_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  respond_to :html, :json

  
end

rod_server/app/controllers/builders_controller.rb
class BuildersController < ApplicationController
  before_action :set_builder, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @builders = Builder.all
    # respond_to do |format|
    #   format.json { render @builders.as_json }
    # end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  def search
    @builders = Builder.search params[:data][:query]
    render json: @builders.as_json
  end

  # GET /groups/new
  def new
    @builder = Builder.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @builder = Builder.new(builder_params)
    @builder.user = current_user

    respond_to do |format|
      if @builder.save
        current_user.builder = @builder
        current_user.save!
        format.html { redirect_to @builder, notice: 'Builder was successfully created.' }
        format.json { render :show, status: :created, location: @builder }
      else
        format.html { render :new }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @builder.update builder_params
        format.html { redirect_to @builder, notice: 'Builder was successfully updated.' }
        format.json { render :show, status: :ok, location: @builder }
      else
        format.html { render :edit }
        format.json { render json: @builder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @builder.destroy
    respond_to do |format|
      format.html { redirect_to builders_url, notice: 'Builder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_builder
      @builder = Builder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def builder_params
      params.require(:builder).permit(:name, :phone, :bio, :location, :minprice, :maxprice, :ship, :rodtype, :species, :poleblank, :image)
    end
end

rod_server/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    # respond_to do |format|
    #   format.json { render json: @groups.as_json }
    # end
  end
# update model with data (post), push data into model
  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

rod_server/app/controllers/poles_controller.rb
class PolesController < ApplicationController
  before_action :set_pole, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @poles = Pole.all
    # respond_to do |format|
    #   format.json { render json: @poles.as_json }
    # end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @pole = Pole.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @pole = Pole.new(pole_params)

    respond_to do |format|
      if @pole.save
        format.html { redirect_to @pole, notice: 'Pole was successfully created.' }
        format.json { render :show, status: :created, location: @pole }
      else
        format.html { render :new }
        format.json { render json: @pole.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @pole.update(pole_params)
        format.html { redirect_to @pole, notice: 'Pole was successfully updated.' }
        format.json { render :show, status: :ok, location: @pole }
      else
        format.html { render :edit }
        format.json { render json: @pole.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @pole.destroy
    respond_to do |format|
      format.html { redirect_to poles_url, notice: 'Pole was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pole
      @pole = Pole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pole_params
      params.require(:pole).permit(:name)
    end
end

rod_server/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :json
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username)
  end
end

rod_server/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username)
  end
end

rod_server/app/helpers/application_helper.rb
module ApplicationHelper
end

rod_server/app/helpers/groups_helper.rb
module GroupsHelper
end

rod_server/app/views/builders/_form.html.erb
<%= form_for(@builder) do |f| %>
  <% if @builder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@builder.errors.count, "error") %> prohibited this builder from being saved:</h2>

      <ul>
      <% @builder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rod_server/app/views/builders/edit.html.erb
<h1>Editing Builder</h1>

<%= render 'form' %>

<%= link_to 'Show', @builder %> |
<%= link_to 'Back', builders_path %>

rod_server/app/views/builders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builders.each do |builder| %>
      <tr>
        <td><%= builder.name %></td>
        <td><%= builder.phone %></td>
        <td><%= builder.bio %></td>
        <td><%= builder.location %></td>
        <td><%= builder.minprice %></td>
        <td><%= builder.maxprice %></td>
        <td><%= builder.ship %></td>
        <td><%= builder.rodtype %></td>
        <td><%= builder.species %></td>
        <td><%= builder.poleblank %></td>
        <td><%= link_to 'Show', builder %></td>
        <td><%= link_to 'Edit', edit_builder_path(builder) %></td>
        <td><%= link_to 'Destroy', builder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Builder', new_builder_path %>

rod_server/app/views/builders/new.html.erb
<h1>New Builder</h1>

<%= render 'form' %>

<%= link_to 'Back', builders_path %>

rod_server/app/views/builders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Builder:</strong>
  <%= @builder.name %>
  <%= @builder.phone %>
  <%= @builder.bio %>
  <%= @builder.location %>
  <%= @builder.minprice %>
  <%= @builder.maxprice %>
  <%= @builder.ship %>
  <%= @builder.rodtype %>
  <%= @builder.species %>
  <%= @builder.poleblank %>
  <%= link_to image_tag(@post.image.url(:med)), @post.image.url %>
</p>

<%= link_to 'Edit', edit_builder_path(@builder) %> |
<%= link_to 'Back', builders_path %>

rod_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RodBroker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>